### ISSUE TITLE
Some other blogs to add

### ISSUE THREAD

**Issue by ViralBShah** [JuliaGPU/juliagpu.org#1]
http://paocweb.mit.edu/about/paoc-spotlights/new-climate-model-to-be-built-from-the-ground-up

I also added another one from NPS, but I don't think it is showing up.

**Comment by maleadt** [comment]
> I also added another one from NPS, but I don't think it is showing up.

Adding the `.md` extension seems to have fixed that.

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/juliagpu.org/commit/3d78127cb13138cb5c8518d26d8415d2b20e75d9
