### ISSUE TITLE
compiler-paper links not rendered in the CUDA Performance section

### ISSUE THREAD

**Issue by evertrol** [JuliaGPU/juliagpu.org#15]
There are two, presumed, links to "compiler-paper" which don't render as link. These now render as:
> [shown][compiler-paper] 

and

> [the paper][compiler-paper]

These can found in [CUDA performance](https://juliagpu.org/cuda/#performance) paragraph, and the [footnote](https://juliagpu.org/cuda/#fndef:1) of that page.

**Comment by maleadt** [comment]
Thanks! Fixed in https://github.com/JuliaGPU/juliagpu.org/commit/e9ebf0c2978e3764460f1104dd16280d9e8407ad
