### ISSUE TITLE
Suggestion: Make RSS feed easier to find

### ISSUE THREAD

**Issue by JordyScript** [JuliaGPU/juliagpu.org#19]
First of all, thanks for all of your hard work.

I like to subscribe to RSS feeds of projects I'm interested in. I couldn't find any clear indication that the JuliaGPU blog supported RSS on the website, until I dug into the source code published here and figured out that I had to use the url: `https://juliagpu.org/post/index.xml` to get my RSS reader to pick it up. 

Now, maybe I've not searched the website long enough and the RSS feed is actually visible on there somewhere, or maybe I couldn't find it because it's not visibly advertised, but either way it would be nice if it could be made more obvious to viewers that there is in fact an RSS feed and the corresponding URL could be made available easily.

**Comment by maleadt** [comment]
There's an RSS logo at the bottom of https://juliagpu.org/post/. I guess it could be made a little more explicit.

**Comment by JordyScript** [comment]
My bad! I can't believe I hadn't noticed that. 

Putting the RSS icon visually next to the `<h1 id="blog"><a href="#blog" class="header-anchor">Blog</a></h1>` element should make it more obvious. 

If that isn't possible, it would stil be more discoverable if it had a subtext containing the string RSS, since I wasn't able to find anything with a `ctrl + f` search.

I do believe that putting the icon all the way at the bottom is a suboptimal placement since by the very nature of the blog most people will only look at the most recent blog posts and never scroll down to the bottom of the page. RSS is a feature that is primarily intended to notify of new posts, so it makes sense conceptually for it to be at the top.

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/juliagpu.org/commit/ad061977b89dc156cdbe32eb225fe8ada368ab71
