### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaGPU/juliagpu.org#3]
Hi,

On https://juliagpu.org link for "NVIDIA CUDA" is broken (and also at least "AMD GPUs") despite best supported  GPU.

I suppose it's because web site was restructured, and I'm just not sure how to fix. so only letting you know.

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/juliagpu.org/commit/86ef30f1a88af17fa41f2af008498b961a424568
