### ISSUE TITLE
Mention the new CUDA.jl package?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaGPU/juliagpu.org#6]
Currently, the JuliaGPU package does not mention the CUDA.jl package.

**Comment by maleadt** [comment]
Ah yes, still need to update this website. On second thought, let's wait until there's a 1.0 release at least (which there will be soon).

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/juliagpu.org/commit/f5dbcfd7add605f4d7f78f8785bddf5d12d203cc
