### ISSUE TITLE
Next round of website / docs improvements

### ISSUE THREAD

**Issue by ViralBShah** [JuliaGPU/juliagpu.org#7]
- [x] Showcase/list the user packages - the breadth by domain
- [x] Add a button for docs on the NVDIA/AMD pages. Add quick links from landing page.
- [x] Add Intel GPU section
- [x] OpenCL - delete the 0.6 stuff 
- [x] CUDA.jl should have some CuArrays docs. At least say something about what works and what doesn't. Show a few examples.
- [x] How to do linear algebra?

**Comment by maleadt** [comment]
Array and linalg documentation added in https://github.com/JuliaGPU/CUDA.jl/pull/227

**Comment by ViralBShah** [comment]
I feel like AMD, Intel and OpenCL all could be on one page and "Other platforms" menu item. It looks extremely sparse the way it is. As they become more sophisticated, they can then have their own page.

**Comment by maleadt** [comment]
Docs are live: https://juliagpu.gitlab.io/CUDA.jl/usage/array/



> I feel like AMD, Intel and OpenCL all could be on one page and "Other platforms" menu item. It looks extremely sparse the way it is. As they become more sophisticated, they can then have their own page.

Makes sense. I also considered putting all back-ends in a drop-down, in the case we get more.

**Comment by ViralBShah** [comment]
Should we do docs.juliagpu.org for the documentation?

**Comment by maleadt** [comment]
> Should we do docs.juliagpu.org for the documentation?

We don't have cross-vendor documentation, and linking to the CUDA.jl docs directly from docs.juliagpu.org doesn't seem ideal to me.

**Comment by ViralBShah** [comment]
I just meant using our domain instead of the generic one. The rest of the path would still be the same.
